apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: {{ .Chart.Name }}
        enabled: "true"
    name: {{ .Chart.Name }}
    namespace: {{ .Values.namespace }}
spec:
    replicas:  {{ .Values.replicaCount }} 
    selector:
        matchLabels:
            app: {{ .Chart.Name }}
            enabled: "true"
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: {{ .Chart.Name }}
                enabled: "true"
        spec:
            containers:
            -   image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                imagePullPolicy: {{ .Values.image.pullPolicy }}
                name: {{ .Chart.Name }}
                resources:
                    {{- toYaml .Values.resources | nindent 20 }}
                ports:
                -   containerPort: {{ .Values.containerPort }}
                    protocol: TCP
                livenessProbe:
                    {{- toYaml .Values.livenessProbe | nindent 20 }}
                readinessProbe:
                    {{- toYaml .Values.readinessProbe | nindent 20 }}