apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ .Chart.Name }}
        enabled: "true"
    name: {{ .Chart.Name }}
    namespace: {{ .Values.namespace }}
spec:
    ports:
    -   port: {{ .Values.service.port }}
        protocol: {{ .Values.service.protocol }}
        targetPort: {{ .Values.service.targetPort }}
    selector:
        app: {{ .Chart.Name }}
        enabled: "true"
    type: {{ .Values.service.type }}